version: '3.8'
services:
  alertbridge:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.41.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - alertbridge

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  ngrok:
    image: wernight/ngrok:latest
    command: ngrok http alertbridge:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - alertbridge
