services:
  alertbridge:
    build: .
    env_file:
      - .env.local
    ports:
      - "8080:8080"
  ngrok:
    image: ngrok/ngrok:latest
    command: ngrok http alertbridge:8080
    ports:
      - "4040:4040"

