version: '3.8'
services:
  alertbridge:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - alertbridge

  ngrok:
    image: wernight/ngrok:1.7.1
    command: ngrok http alertbridge:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - alertbridge

volumes:
  caddy_data:
  caddy_config:
