services:
  ngrok:
    image: ngrok/ngrok:latest
    env_file:
      - .env.local
    command: http alertbridge:8080
    depends_on:
      - alertbridge
    ports:
      - "4040:4040"
    # environment:
    #   - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}

