# This is a sample configuration for a production environment using Docker Compose.
# TODO: Pull alertbridge image from ghcr.io instead of building locally.
services:
  caddy:
    image: caddy:2
    env_file:
      - .env.production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - alertbridge

volumes:
  caddy_data:
  caddy_config:
