name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
    - name: Install syft
      run: |
        curl --fail --silent --show-error -L https://raw.githubusercontent.com/anchore/syft/v0.84.0/install.sh | sh -s -- -b /usr/local/bin
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
    - name: go vet
      run: go vet ./...
    - name: go test
      run: go test ./... -coverprofile=coverage.out
    - name: go tool cover
      run: go tool cover -func=coverage.out
    - name: govulncheck
      run: govulncheck ./... > govulncheck.txt
    - name: syft sbom
      run: syft dir . -o spdx-json > sbom.spdx
    - name: staticcheck
      run: staticcheck ./... > staticcheck.txt
    - name: Upload staticcheck results
      uses: actions/upload-artifact@v3
      with:
        name: staticcheck
        path: staticcheck.txt
    - name: Upload govulncheck results
      uses: actions/upload-artifact@v3
      with:
        name: govulncheck
        path: govulncheck.txt
    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: sbom.spdx
